# Generated by Django 4.1.3 on 2022-12-31 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "house_no",
                    models.IntegerField(default=0, verbose_name="House Number"),
                ),
                (
                    "street_name",
                    models.CharField(
                        max_length=500, verbose_name="Street Name"
                    ),
                ),
                (
                    "bus_stop",
                    models.CharField(
                        max_length=60, verbose_name="Nearest Bus Stop"
                    ),
                ),
                ("lga", models.CharField(max_length=60, verbose_name="LGA")),
                (
                    "postal_code",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="LGA Postal Code",
                    ),
                ),
                (
                    "state",
                    models.CharField(max_length=60, verbose_name="State"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Nigeria", max_length=60, verbose_name="Country"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_address",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User's Address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "ordering": ["added_on"],
            },
        ),
    ]
