# Generated by Django 4.1.3 on 2023-01-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_alter_address_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="house_no",
            field=models.CharField(max_length=5, verbose_name="House Number"),
        ),
    ]
