# Generated by Django 4.1.3 on 2023-01-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0003_alter_address_house_no"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ["-added_on"],
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=6,
                null=True,
                verbose_name="LGA Postal Code",
            ),
        ),
    ]
