# Generated by Django 4.1.3 on 2023-01-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0004_alter_address_options_alter_address_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="LGA Postal Code"
            ),
        ),
    ]
