# Generated by Django 4.1.3 on 2022-12-29 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dob",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                null=True,
                verbose_name="Date of Birth",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                default="",
                max_length=14,
                null=True,
                verbose_name="Gender",
            ),
        ),
    ]
