# Generated by Django 4.1.3 on 2022-12-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                verbose_name="11-digit Phone Number",
            ),
        ),
    ]
