# Generated by Django 4.1.3 on 2022-12-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_dob_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="11-digit Phone Number",
            ),
        ),
    ]
