# Generated by Django 4.1.3 on 2022-12-11 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="category",
            name="meta_keywords",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="meta_keywords",
        ),
        migrations.CreateModel(
            name="LowerSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="format: required, max_length=100",
                        max_length=100,
                        verbose_name="Lower Subcategory Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="format: required, letters, numbers, underscore, or hyphens",
                        max_length=100,
                        unique=True,
                        verbose_name="Lower Subcategory URL",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="main_subcategory",
                        to="inventory.subcategory",
                        verbose_name="Main Subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lower Subcategory",
                "verbose_name_plural": "Lower Subcategories",
                "ordering": ["-created_at"],
            },
        ),
    ]
