# Generated by Django 4.1.3 on 2022-12-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lowersubcategory",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Lower Subcategory",
                "verbose_name_plural": "Lower Subcategories",
            },
        ),
        migrations.RemoveField(
            model_name="producttype",
            name="product_type_icon",
        ),
    ]
