# Generated by Django 4.1.3 on 2022-12-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattribute",
            name="name",
            field=models.CharField(
                help_text="format: required, unique, max_length-100",
                max_length=100,
                verbose_name="Product Attribute Name",
            ),
        ),
    ]
