# Generated by Django 4.1.3 on 2022-12-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_category_meta_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lowersubcategory",
            name="slug",
            field=models.SlugField(
                help_text="format: required, letters, numbers, underscore, or hyphens",
                max_length=100,
                verbose_name="Lower Subcategory URL",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(
                help_text="format: required, letters, numbers, underscore, or hyphens",
                max_length=100,
                verbose_name="Subcategory URL",
            ),
        ),
    ]
