# Generated by Django 4.1.3 on 2022-12-23 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_lowersubcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="lowersubcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lowersubcategory",
                to="inventory.lowersubcategory",
                verbose_name="Lower Subcategory",
            ),
        ),
    ]
