# Generated by Django 4.1.3 on 2022-12-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0003_alter_lowersubcategory_slug_alter_subcategory_slug",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lowersubcategory",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="main_subcategories",
                to="inventory.subcategory",
                verbose_name="Main Subcategory",
            ),
        ),
    ]
