# Generated by Django 4.1.3 on 2022-12-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_product_flashsale_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="flashsale",
        ),
    ]
