# Generated by Django 4.1.3 on 2022-12-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_lowersubcategory_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lowersubcategory",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lowersubcategories",
                to="inventory.subcategory",
                verbose_name="Main Subcategory",
            ),
        ),
    ]
