# Generated by Django 4.1.3 on 2022-12-07 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_product_flashsale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="flashsale_price",
        ),
        migrations.AddField(
            model_name="product",
            name="flashsale",
            field=models.IntegerField(
                default=0,
                help_text="format: how many percent off the  regular price of product",
                verbose_name="Percentage Off",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_images",
                to="inventory.product",
                verbose_name="Product Image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="format: regular price of product",
                max_digits=15,
                verbose_name="Regular Price",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_stock",
                to="inventory.product",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcategories",
                to="inventory.category",
                verbose_name="Main Category",
            ),
        ),
    ]
