# Generated by Django 4.1.3 on 2022-12-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_lowersubcategory_subcategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="lowersubcategory",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Lower Subcategory",
                "verbose_name_plural": "Lower Subcategories",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Subcategory",
                "verbose_name_plural": "Subcategories",
            },
        ),
    ]
