# Generated by Django 4.1.3 on 2022-12-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0005_remove_product_flashsale_price_product_flashsale_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                help_text="format: regular price of product",
                verbose_name="Regular Price",
            ),
        ),
    ]
