# Generated by Django 4.1.3 on 2022-12-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
