# Generated by Django 4.1.3 on 2022-12-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_product_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashsaleCtrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="format: required, max_length-255",
                        max_length=100,
                        verbose_name="Alternative Text",
                    ),
                ),
                ("when", models.DateTimeField()),
            ],
        ),
    ]
