# Generated by Django 4.1.3 on 2022-12-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_flashsalectrl"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashsalectrl",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="format: default=false, true = flashsale is active",
                verbose_name="Active Flashsale",
            ),
        ),
        migrations.AlterField(
            model_name="flashsalectrl",
            name="name",
            field=models.CharField(
                help_text="format: required, max_length-100",
                max_length=100,
                verbose_name="Flashsale Name",
            ),
        ),
    ]
