# Generated by Django 4.1.3 on 2022-12-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lowersubcategory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Lower Subcategory",
                "verbose_name_plural": "Lower Subcategories",
            },
        ),
    ]
