# Generated by Django 4.1.3 on 2022-12-21 03:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_alter_product_attribute_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_nav_image",
            field=cloudinary.models.CloudinaryField(
                default="", max_length=255, verbose_name="Image"
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="product_type_icon",
            field=cloudinary.models.CloudinaryField(
                default="", max_length=255, verbose_name="Image"
            ),
        ),
    ]
