# Generated by Django 4.1.3 on 2022-12-21 10:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_category_category_nav_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="Category Banner Image"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_nav_image",
            field=cloudinary.models.CloudinaryField(
                default="", max_length=255, verbose_name="Category Nav Image"
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="product_type_icon",
            field=cloudinary.models.CloudinaryField(
                default="", max_length=255, verbose_name="Product Type Icon"
            ),
        ),
    ]
