# Generated by Django 4.1.3 on 2022-12-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_alter_category_category_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="format: optional",
                null=True,
                verbose_name="Subcategory Description",
            ),
        ),
    ]
